repository:
  name: asdf-go-jsonnet
  description: go-jsonnet tools plugin for asdf version manager
  homepage: https://github.com/asdf-vm/asdf
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  topics: asdf, version-manager, asdf-plugin, jsonnet, go-jsonnet
labels:
- name: bug
  color: CC0000
- name: feature
  color: 336699
